languageCode = "fr"
baseurl = "http://example.com/"
title = "Hugo Tailwindcss Starter"

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    favicon = "favicon.ico"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
